# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "7"

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version

test_script:
  - npm test
