/**
 * Regenerates `src/version.ts` from the `package.json` version.
 *
 * The library cannot import `package.json` directly: per-file tsc emit ships
 * the import verbatim, where Node ESM requires a `type: 'json'` attribute and
 * browsers cannot load JSON modules at all. A generated, committed constant is
 * environment-neutral. Sync is enforced by `scripts/check-version.ts` (release
 * gate) and the `VERSION matches the package manifest` test in
 * `src/index.test.ts` (CI gate).
 *
 * Run after every version bump: `bun run generate:version`.
 */

import pkg from '../package.json' with { type: 'json' };

const TARGET = new URL('../src/version.ts', import.meta.url);

const content = `// Generated by \`bun run generate:version\` from package.json — do not edit.
export const version = '${pkg.version}';
`;

const previous = (await Bun.file(TARGET).exists()) ? await Bun.file(TARGET).text() : null;

if (previous === content) {
  console.log(`src/version.ts already at ${pkg.version}`);
} else {
  await Bun.write(TARGET, content);
  console.log(`src/version.ts → ${pkg.version}`);
}
